# Generated by Django 2.2.10 on 2020-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetables'), ('D', 'Dairy'), ('FG', 'Foodgrains'), ('O', 'Oil'), ('PF', 'Pet Food'), ('R', 'Rice'), ('M', 'Masalas'), ('B', 'Beverages')], max_length=2),
        ),
    ]
